import type { Snapshot } from "./types";

// Seed data used by DEMO MODE (localStorage) and by the Apps Script
// installer to pre-populate an empty spreadsheet.
export function seedSnapshot(): Snapshot {
  const now = new Date().toISOString();
  const base = new Date();
  const dayOff = (n: number) => {
    const x = new Date(base);
    x.setDate(base.getDate() + n);
    return x.toISOString().slice(0, 10);
  };
  return {
    profile: {
      name: "Hanafi Afan",
      role: "Full-Stack Software Developer",
      email: "hanafi.afan@gmail.com",
      location: "Bandung, Indonesia",
      bio: "Software developer berfokus pada web & mobile app development. Suka membangun produk yang rapi, scalable, dan enak dipakai.",
      avatarEmoji: "",
      skills: ["TypeScript", "Next.js", "Laravel", "Flutter", "PostgreSQL", "Node.js", "Tailwind"],
      github: "https://github.com/hanafiafan",
      linkedin: "https://linkedin.com/in/hanafiafan",
      website: "https://hanafiafan.dev",
      showCalendar: true,
      showTechStack: true,
      acceptingProjects: true,
    },
    projects: [
      {
        id: "p_ecommerce",
        name: "E-Commerce Platform",
        emoji: "cart",
        status: "In Progress",
        priority: "High",
        startDate: "2026-04-01",
        deadline: "2026-07-15",
        techStack: ["Next.js", "Laravel", "MySQL", "Tailwind"],
        client: "PT Maju Jaya",
        progress: 62,
        publicSummary: "Full-stack e-commerce dengan payment gateway, cart, checkout, dan admin panel analytics.",
        description:
          "Full-stack e-commerce dengan payment gateway (Midtrans), cart, checkout, dan admin panel analytics.",
        repoUrl: "https://github.com/hanafiafan/ecommerce",
        figmaUrl: "https://figma.com/file/ecommerce",
        stagingUrl: "https://staging.ecom.test",
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "p_mbanking",
        name: "Mobile Banking App",
        emoji: "bank",
        status: "In Progress",
        priority: "High",
        startDate: "2026-05-10",
        deadline: "2026-09-01",
        techStack: ["Flutter", "Firebase", "Node.js"],
        client: "Bank Digital X",
        progress: 35,
        publicSummary: "Aplikasi mobile banking dengan biometric login, transfer, QRIS, dan notifikasi real-time.",
        description: "Aplikasi mobile banking dengan biometric login, transfer, QRIS, dan notifikasi real-time.",
        repoUrl: "https://github.com/hanafiafan/mbanking",
        figmaUrl: "",
        stagingUrl: "",
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "p_portfolio",
        name: "Portfolio Website",
        emoji: "design",
        status: "Planning",
        priority: "Medium",
        startDate: "2026-06-20",
        deadline: "2026-07-10",
        techStack: ["Astro", "Tailwind", "MDX"],
        client: "Personal",
        progress: 5,
        publicSummary: "Personal portfolio + blog dengan MDX, dark mode, dan animasi halus.",
        description: "Personal portfolio + blog dengan MDX, dark mode, dan animasi halus.",
        repoUrl: "",
        figmaUrl: "",
        stagingUrl: "",
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "p_inventory",
        name: "Inventory Management System",
        emoji: "box",
        status: "Planning",
        priority: "Low",
        startDate: "2026-07-01",
        deadline: "2026-08-30",
        techStack: ["Vue", "Express", "PostgreSQL"],
        client: "Gudang Sejahtera",
        progress: 0,
        publicSummary: "Sistem manajemen stok gudang dengan barcode scanner dan laporan stok otomatis.",
        description: "Sistem manajemen stok gudang dengan barcode scanner dan laporan stok otomatis.",
        repoUrl: "",
        figmaUrl: "",
        stagingUrl: "",
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "p_company",
        name: "Company Profile Redesign",
        emoji: "web",
        status: "Completed",
        priority: "Medium",
        startDate: "2026-02-01",
        deadline: "2026-04-15",
        techStack: ["WordPress", "PHP"],
        client: "CV Berkah",
        progress: 100,
        publicSummary: "Redesign company profile + SEO optimization. Sudah live & diserahterimakan.",
        description: "Redesign company profile + SEO optimization. Sudah live & diserahterimakan.",
        repoUrl: "",
        figmaUrl: "",
        stagingUrl: "https://berkah.co.id",
        isPublic: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      task("t1", "p_ecommerce", "Integrasi payment gateway Midtrans", "Done", "High", "2026-06-11", 8),
      task("t2", "p_ecommerce", "Refactor cart & checkout logic", "In Progress", "High", "2026-06-14", 6, "Edge case kupon"),
      task("t3", "p_ecommerce", "Admin dashboard analytics", "Todo", "Medium", "2026-06-20", 10),
      task("t4", "p_ecommerce", "Fix bug image upload S3", "Blocked", "High", "2026-06-12", 3, "Nunggu akses bucket"),
      task("t5", "p_mbanking", "Biometric login flow", "Done", "High", "2026-06-10", 12),
      task("t6", "p_mbanking", "Implement QRIS transfer", "In Progress", "High", "2026-06-18", 14),
      task("t7", "p_mbanking", "Push notification service", "Todo", "Medium", "2026-06-25", 8),
      task("t8", "p_portfolio", "Pilih design system & wireframe", "Todo", "Medium", "2026-06-22", 4),
      task("t9", "p_inventory", "Database schema design", "Todo", "Low", "2026-07-05", 5),
      task("t10", "p_company", "Final SEO audit", "Done", "Medium", "2026-04-14", 4),
    ],
    events: [
      { id: "e1", title: "Daily standup", date: dayOff(0), time: "09:00", type: "Meeting", notes: "Sync progress harian", createdAt: now },
      { id: "e2", title: "Client call — PT Maju Jaya", date: dayOff(0), time: "14:00", type: "Meeting", notes: "Demo fitur checkout", createdAt: now },
      { id: "e3", title: "Deadline: QRIS transfer", date: dayOff(2), time: "", type: "Deadline", notes: "", createdAt: now },
      { id: "e4", title: "Review code PR #42", date: dayOff(3), time: "16:00", type: "Reminder", notes: "", createdAt: now },
      { id: "e5", title: "Belajar Rust", date: dayOff(5), time: "20:00", type: "Personal", notes: "Bab ownership", createdAt: now },
    ],
    requests: [
      {
        id: "r_sample",
        name: "Budi Santoso",
        whatsapp: "+6281234567890",
        email: "budi@tokokita.id",
        company: "Toko Kita",
        projectType: "Website / Web App",
        budget: "Rp 5 - 15 juta",
        timeline: "1-2 bulan",
        referenceUrl: "",
        driveLink: "",
        message:
          "Halo, saya butuh dibuatkan landing page untuk toko online saya beserta integrasi WhatsApp checkout. Mohon info estimasi waktu & biaya.",
        attachments: [],
        status: "New",
        createdAt: now,
      },
    ],
    activity: [
      {
        id: "a1",
        timestamp: now,
        type: "project",
        action: "created",
        message: "Workspace di-inisialisasi dengan data contoh",
      },
    ],
  };

  function task(
    id: string,
    projectId: string,
    name: string,
    status: Snapshot["tasks"][number]["status"],
    priority: Snapshot["tasks"][number]["priority"],
    dueDate: string,
    estimatedHours: number,
    notes = "",
  ) {
    return {
      id,
      projectId,
      name,
      status,
      priority,
      dueDate,
      estimatedHours,
      notes,
      createdAt: now,
      updatedAt: now,
    };
  }
}
